version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"
