<?php
#wfLoadExtension('AntiSpoof');
wfLoadExtension( 'Apiunto' );
wfLoadExtension( 'ApprovedRevs' );
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Capiunto' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'CookieWarning' );
#wfLoadExtension( 'CommonsMetadata' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'ConfirmEdit/QuestyCaptcha' );
wfLoadExtension( 'Disambiguator' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'LabeledSectionTransclusion' );
wfLoadExtension( 'Linter' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'OAuth' );
wfLoadExtension( 'Plausible' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'RelatedArticles' );
wfLoadExtension( 'SandboxLink' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SimpleTerms' );
wfLoadExtension( 'SwiftMailer' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TemplateStyles' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'TimedMediaHandler' );
wfLoadExtension( 'UploadWizard' );
wfLoadExtension( 'Variables' );
wfLoadExtension( 'VisualEditor' );
# wfLoadExtension( 'WebP' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'WikiSEO' );

wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'Popups' );
