<?php
wfLoadExtension( 'Elastica' );
wfLoadExtension( 'CirrusSearch' );

wfLoadExtension( 'AdvancedSearch' );
#wfLoadExtension('AntiSpoof');
wfLoadExtension( 'Apiunto' );
wfLoadExtension( 'ApprovedRevs' );
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Capiunto' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'CookieWarning' );
#wfLoadExtension( 'CommonsMetadata' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'ConfirmEdit/QuestyCaptcha' );
wfLoadExtension( 'Disambiguator' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'Flow' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'LabeledSectionTransclusion' );
#wfLoadExtension( 'Lingo' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'OAuth' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'RelatedArticles' );
wfLoadExtension( 'SandboxLink' );
wfLoadExtension( 'Scribunto' );
enableSemantics('star-citizen.wiki');
wfLoadExtension( 'SemanticResultFormats' );
wfLoadExtension( 'SemanticScribunto' );
wfLoadExtension( 'SwiftMailer' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TemplateStyles' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'TimedMediaHandler' );
wfLoadExtension( 'UploadWizard' );
wfLoadExtension( 'Variables' );
wfLoadExtension( 'VisualEditor' );
#wfLoadExtension( 'Wiki3d' ); // Wiki3D
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'WikiSEO' );

wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'Popups' );
