version: '3.7'

###
# This file assumes the following external network
# docker network create --subnet=172.16.0.0/29 star-citizen.wiki
#
# And user scwiki (change UID and GID in .env)
###

services:
  star-citizen.wiki-live:
    image: scwiki/wiki:dev
    #image: scwiki/wiki:1.35.0
    container_name: star-citizen.wiki-live
    restart: unless-stopped
    init: true
    user: "www-data:www-data"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db
      - redis
      - elasticsearch
    links:
      - db
    expose:
      - 80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /etc/star-citizen.wiki/LocalSettings.php:/var/www/html/LocalSettings.php
      - /etc/star-citizen.wiki/config:/var/www/config
      - /etc/star-citizen.wiki/.smw.json:/var/www/html/extensions/SemanticMediaWiki/.smw.json
      - /srv/star-citizen.wiki/sitemap:/var/www/html/sitemap
      - /srv/star-citizen.wiki/images:/var/www/html/images
      - /var/lib/star-citizen.wiki/cache:/var/www/cache
      #- /srv/cdn.star-citizen.wiki/images:/var/www/html/images
    networks:
      internal:
    healthcheck:
      test: curl --fail -s http://star-citizen.wiki-live/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 3

  star-citizen.wiki-varnish:
    image: varnish:stable
    container_name: star-citizen.wiki-varnish
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    depends_on:
      - star-citizen.wiki-live
    #expose:
    #  - 80
    ports:
      - 0.0.0.0:8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/star-citizen.wiki/container-config/varnish.vcl:/etc/varnish/default.vcl:ro
    networks:
      star-citizen.wiki:
        ipv4_address: 172.16.0.4
      internal:
    environment:
      VARNISH_SIZE: 1G
    # Find the traefik config at https://github.com/StarCitizenWiki/WikiTraefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=star-citizen.wiki"
      - "traefik.http.routers.star-citizen.rule=Host(`${HOST}`)"
      - "traefik.http.routers.star-citizen.entryPoints=https"
      - "traefik.http.routers.star-citizen.middlewares=default@file,star-citizen-csp@file"
      - "traefik.http.routers.star-citizen.tls=true"
      - "traefik.http.routers.star-citizen.tls.certresolver=dns"
      - "traefik.http.routers.star-citizen.tls.options=default"
      - "traefik.http.routers.star-citizen.tls.domains[0].main=${HOST}"
      - "traefik.http.routers.star-citizen.tls.domains[0].sans=*.${HOST}"

      - "traefik.http.routers.star-citizen-api.rule=Host(`${HOST}`) && (Query(`action=ask`) || Query(`action=query`))"
      - "traefik.http.routers.star-citizen-api.entryPoints=https"
      - "traefik.http.routers.star-citizen-api.middlewares=cdn-star-citizen-headers@file"
      - "traefik.http.routers.star-citizen-api.tls=true"
      - "traefik.http.routers.star-citizen-api.tls.options=default"

  db:
    image: mariadb:latest
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 45s
      interval: 10s
      retries: 5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/star-citizen.wiki/db:/var/lib/mysql
    networks:
      - internal

  elasticsearch:
    image: docker-registry.wikimedia.org/dev/stretch-elasticsearch:0.0.1
    restart: unless-stopped
    init: true
    user: "${UID}:0"
    security_opt:
      - no-new-privileges:true
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/star-citizen.wiki/esdata:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    networks:
      - internal

  ofelia:
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    depends_on:
      - star-citizen.wiki-live
      - db
      - elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/star-citizen.wiki/container-config/ofelia.ini:/etc/ofelia/config.ini:ro

  redis:
    image: redis:alpine
    restart: unless-stopped
    init: true
    user: "${UID}:${GID}"
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/star-citizen.wiki/redis:/data

networks:
  star-citizen.wiki:
    external: true
  internal:
