version: '3.7'

###
# This file assumes the following external network
# docker network create --subnet=172.16.0.0/29 star-citizen.wiki
###

services:
  star-citizen.wiki_live:
    image: scw-wiki:1.35.0
    container_name: star-citizen.wiki_live
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db
      - elasticsearch
    links:
      - db
    expose:
      - 80
    #ports:
    #- 127:0.0.1:80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/star-citizen.wiki/LocalSettings.php:/var/www/html/LocalSettings.php
      - /etc/star-citizen.wiki/config:/var/www/config
      - /etc/star-citizen.wiki/.smw.json:/var/www/html/extensions/SemanticMediaWiki/.smw.json
      - /etc/star-citizen.wiki/includes/libs/mime/MimeMap.php:/var/www/html/includes/libs/mime/MimeMap.php:ro
      - /etc/star-citizen.wiki/container-config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - /etc/star-citizen.wiki/container-config/robots.txt:/var/www/html/robots.txt:ro
      - /etc/star-citizen.wiki/container-config/favicon.ico:/var/www/html/favicon.ico:ro
      - /srv/star-citizen.wiki/sitemap:/var/www/html/sitemap
      - /srv/cdn.star-citizen.wiki/images:/var/www/html/images
    networks:
      star-citizen.wiki:
        ipv4_address: 172.16.0.3
      internal:
    healthcheck:
      test: curl --fail -s http://172.16.0.3/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=star-citizen.wiki"
      - "traefik.http.routers.star-citizen.rule=Host(`star-citizen.wiki`)"
      - "traefik.http.routers.star-citizen.entryPoints=https"
      - "traefik.http.routers.star-citizen.middlewares=default@file,star-citizen-csp@file"
      - "traefik.http.routers.star-citizen.tls=true"
      - "traefik.http.routers.star-citizen.tls.certresolver=dns"
      - "traefik.http.routers.star-citizen.tls.options=default"
      - "traefik.http.routers.star-citizen.tls.domains[0].main=star-citizen.wiki"
      - "traefik.http.routers.star-citizen.tls.domains[0].sans=*.star-citizen.wiki"

  db:
    image: mariadb:latest
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "db", "-u", "root", "-pCHANGEME" ]
      timeout: 45s
      interval: 10s
      retries: 5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/star-citizen.wiki/db:/var/lib/mysql
    networks:
      - internal

  elasticsearch:
    image: docker-registry.wikimedia.org/dev/stretch-elasticsearch:0.0.1
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/lib/star-citizen.wiki/esdata:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    networks:
      - internal

  ofelia:
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    depends_on:
      - star-citizen.wiki_live
      - db
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/star-citizen.wiki/container-config/ofelia.ini:/etc/ofelia/config.ini:ro

  redis:
    image: redis:alpine
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    networks:
      - internal

networks:
  star-citizen.wiki:
    external: true
  internal:
